# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finderApp', '0002_remove_ingredient_ingredient_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='picture_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
