# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-02 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finderApp', '0004_auto_20160401_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='creater',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
