# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-02 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finderApp', '0006_auto_20160402_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='catogery',
            new_name='category',
        ),
    ]
